DOMAIN = "notifyai"
CONF_API_KEY = "api_key"
CONF_MODEL = "model"
CONF_NOTIFY_SERVICE_1 = "notify_service_1"
CONF_NOTIFY_SERVICE_2 = "notify_service_2"
CONF_NOTIFY_SERVICE_3 = "notify_service_3"
CONF_NOTIFY_SERVICE_4 = "notify_service_4"
